### ISSUE TITLE
Some issue with arranger panel

### ISSUE THREAD

**Issue by hajdam** [jjazzboss/JJazzLab-X#260]
JJazzLab 3.0.2a on Fedora Linux, Java 11 OpenJDK

```
java.lang.NullPointerException
	at org.jjazz.arranger.Arranger.updateChordSymbol(Arranger.java:211)
	at org.jjazz.arranger.ArrangerPanel.processIncomingChord(ArrangerPanel.java:417)
	at org.jjazz.arranger.ChordReceiver.lambda$fireChordChanged$0(ChordReceiver.java:188)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.jjazz.arranger.ChordReceiver.fireChordChanged(ChordReceiver.java:188)
	at org.jjazz.arranger.ChordReceiver.send(ChordReceiver.java:161)
	at org.jjazz.midi.api.device.MidiFilter.passed(MidiFilter.java:118)
	at org.jjazz.midi.api.device.MidiFilter$FilterReceiver.send(MidiFilter.java:162)
	at java.desktop/com.sun.media.sound.AbstractMidiDevice$TransmitterList.sendMessage(Unknown Source)
	at java.desktop/com.sun.media.sound.MidiInDevice.callbackShortMessage(Unknown Source)
	at java.desktop/com.sun.media.sound.MidiInDevice.nGetMessages(Native Method)
	at java.desktop/com.sun.media.sound.MidiInDevice.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jjazzboss** [comment]
do you have more info how it happened ?

**Comment by hajdam** [comment]
Sorry, not sure. Maybe it was because I connected the keyboard after I started the application. I restarted application and arranger window seemed to be working again...

**Comment by hajdam** [comment]
Reproduced with following steps:
- start app and select column in structure editor
- start playback in arranger (via button)
- stop playback in arranger (via button)
- on external MIDI keyboard press chord combination (while arranger is stopped)

**Comment by jjazzboss** [comment]
Great, I could reproduce it I'll investigate

**Comment by jjazzboss** [comment]
ok that was an easy, fixed for next release.
