### ISSUE TITLE
Song part editor disappeared

### ISSUE THREAD

**Issue by jjazzboss** [jjazzboss/JJazzLab-X#50]
Hello, I have been able to create several backing tracks but now I am now unable to view and adjust the parameters for each section i.e mute intensity etc.
I have uninstalled and reinstalled the program several times
 Can you help?

at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)
at org.jjazz.ui.spteditor.SptEditor.updateUIComponents(SptEditor.java:494)
at org.jjazz.ui.spteditor.SptEditor.refresh(SptEditor.java:408)
at org.jjazz.ui.spteditor.SptEditor.songPresenceChanged(SptEditor.java:477)
at org.jjazz.ui.spteditor.SptEditor.<init>(SptEditor.java:159)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.<init>(SptEditorTopComponent.java:82)
at jdk.internal.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:75)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:203)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:74)
at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:292)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)
at org.jjazz.ui.spteditor.SptEditor.updateUIComponents(SptEditor.java:494)
at org.jjazz.ui.spteditor.SptEditor.refresh(SptEditor.java:408)
at org.jjazz.ui.spteditor.SptEditor.songPresenceChanged(SptEditor.java:477)
at org.jjazz.ui.spteditor.SptEditor.<init>(SptEditor.java:159)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.<init>(SptEditorTopComponent.java:82)
at jdk.internal.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:75)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:203)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:74)
at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:292)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)
at org.jjazz.ui.spteditor.SptEditor.updateUIComponents(SptEditor.java:494)
at org.jjazz.ui.spteditor.SptEditor.refresh(SptEditor.java:408)
at org.jjazz.ui.spteditor.SptEditor.songPresenceChanged(SptEditor.java:477)
at org.jjazz.ui.spteditor.SptEditor.<init>(SptEditor.java:159)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.<init>(SptEditorTopComponent.java:82)
at jdk.internal.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:75)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:203)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:74)
at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:292)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)
at org.jjazz.ui.spteditor.SptEditor.updateUIComponents(SptEditor.java:494)
at org.jjazz.ui.spteditor.SptEditor.refresh(SptEditor.java:408)
at org.jjazz.ui.spteditor.SptEditor.songPresenceChanged(SptEditor.java:477)
at org.jjazz.ui.spteditor.SptEditor.<init>(SptEditor.java:159)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.<init>(SptEditorTopComponent.java:82)
at jdk.internal.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:75)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:203)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:74)
at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:292)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)
at org.jjazz.ui.spteditor.SptEditor.updateUIComponents(SptEditor.java:494)
at org.jjazz.ui.spteditor.SptEditor.refresh(SptEditor.java:408)
at org.jjazz.ui.spteditor.SptEditor.songPresenceChanged(SptEditor.java:477)
at org.jjazz.ui.spteditor.SptEditor.<init>(SptEditor.java:159)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.<init>(SptEditorTopComponent.java:82)
at jdk.internal.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:75)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:203)
at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:74)
at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:292)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
at org.jjazz.ui.spteditor.api.SptEditorTopComponent.getInstance(SptEditorTopComponent.java:95)
at org.jjazz.ui.spteditor.SptEditor.updateTabName(SptEditor.java:638)

**Comment by jjazzboss** [comment]
Should be fixed with implementation of Issue #42
